# Generated by Django 2.2.6 on 2019-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_task', '0003_auto_20191029_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('added', 'Added'), ('inprogress', 'Inprogress'), ('completed', 'Completed')], default='added', max_length=15),
        ),
    ]
